const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');
const PDFDocument = require('pdfkit');
const { success, error, downloadUrl, outputPath } = require('../utils/response');
const { deleteFile } = require('../utils/cleanup');

module.exports = async (req, res) => {
  const { name, description, price, category, sku } = req.body;
  if (!name) return error(res, 'Product name is required');

  const outName = `${uuidv4()}.pdf`;
  const outPath = outputPath(outName);
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const stream = fs.createWriteStream(outPath);
  doc.pipe(stream);

  // Header bar
  doc.rect(0, 0, doc.page.width, 80).fill('#5a60ff');
  doc.fillColor('#ffffff').fontSize(26).font('Helvetica-Bold')
    .text('PRODUCT SHEET', 50, 25, { align: 'left' });
  doc.fontSize(11).font('Helvetica').fillColor('#d0d2ff')
    .text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 50, 55);

  let y = 110;

  // Product image (if uploaded)
  if (req.file) {
    try {
      doc.image(req.file.path, 50, y, { width: 180, height: 180 });
    } catch (_) {}
  }

  const textX = req.file ? 260 : 50;
  const textW = req.file ? 285 : 495;

  // Product name
  doc.fillColor('#1a1a2e').fontSize(22).font('Helvetica-Bold')
    .text(name, textX, y, { width: textW });
  y = doc.y + 8;

  if (category) {
    doc.fillColor('#5a60ff').fontSize(11).font('Helvetica')
      .text(`Category: ${category}`, textX, y, { width: textW });
    y = doc.y + 6;
  }

  if (sku) {
    doc.fillColor('#888').fontSize(10).font('Helvetica')
      .text(`SKU: ${sku}`, textX, y, { width: textW });
    y = doc.y + 6;
  }

  if (price) {
    doc.fillColor('#16a34a').fontSize(20).font('Helvetica-Bold')
      .text(`$${price}`, textX, y, { width: textW });
    y = doc.y + 12;
  }

  if (description) {
    doc.fillColor('#444').fontSize(11).font('Helvetica')
      .text(description, textX, y, { width: textW });
  }

  // Divider
  const divY = Math.max(doc.y, req.file ? 310 : doc.y) + 20;
  doc.moveTo(50, divY).lineTo(doc.page.width - 50, divY).strokeColor('#e0e0f0').lineWidth(1).stroke();

  // Footer
  doc.fillColor('#aaa').fontSize(9).font('Helvetica')
    .text('Generated by PDF Tools · pdftools.com', 50, divY + 10, { align: 'center', width: 495 });

  doc.end();

  stream.on('finish', () => {
    if (req.file) deleteFile(req.file.path);
    success(res, {
      message: 'Product PDF generated successfully',
      filename: outName,
      downloadUrl: `${downloadUrl(req, outName)}?name=Product PDF`,
    });
  });

  stream.on('error', (err) => {
    if (req.file) deleteFile(req.file.path);
    error(res, `PDF generation failed: ${err.message}`, 500);
  });
};
